server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employeeskiran
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    oauth2-redirect-url: http://localhost:8080/swagger-ui/oauth2-redirect.html
    operations-sorter: method
    default-models-expand-depth: -1
    doc-expansion: none
    persist-authorization: true
jwt:
  secret: MyUltraSecretKeyThatIsSecureEnough123456
  expiration: 7200000
